thin-edge/tedge-container-bundle

.github/workflows/test.yaml, Dockerfile, README.md, docker-compose.yaml, scripts/manage.sh
Until 1.3.0 is released, use tedge-main by default.
=> chore: use tedge-main by default

justfile
Older docker versions, e.g. docker 18.x and some early 19.x versions don't support the newer oci media type, and result in the following error when pulling the image:
```
docker: mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'
```
=> feat: disable oci images for improved compatibility

Dockerfile
Remove temporary files left over from the s6-overlay installation
=> fix: remove temp s6-overlay installation files

Dockerfile
Initialize the c8y-remote-access-plugin until the upstream PR is merged: https://github.com/thin-edge/thin-edge.io/pull/3120
=> fix: initialize the c8y-remote-access-plugin

Dockerfile
Include docker-cli and the tedge-container-plugin by default to allow managing other containers
=> feat: include container management by default

README.md
Updated instructions to run the container in README. Docker reported for the existing one `docker: Conflicting options: --restart and --rm.`
=> fix example in readme (--rm and --restart conflicting options)

Dockerfile
Update to thin-edge.io 1.3.0 and remove some workaround which are no longer needed
=> chore: update to thin-edge.io 1.3.0

Dockerfile, README.md, docker-compose.yaml, files/tedge/plugins/tedge-log-plugin.toml, files/tedge/self.sh, files/tedge/self_update.sh, files/tedge/self_update.toml, files/tedge/software_update.toml, justfile, tests/main/self-update.robot
Support self updates via Cumulocity via the `self` software management plugin type.
It is still deemed "experimental" as there are still some cleanup to do so that it works in more scenarios (plus the docs have not been updated)
=> feat: support self update via cloud

Dockerfile
Update thin-edge.io s6-overlay service definitions which no longer requires gnu sed logging purposes.
=> feat: remove gnu sed dependency

Dockerfile, files/tedge/c8y_RemoteAccessConnect, files/tedge/launch-remote-access.sh
Launching in the background enables the session to be independent of the parent container. This opens up the possibility to perform maintaince/updates on the parent container in the ssh session.
=> feat: launch remote-access session in separate container

Dockerfile, files/tedge/container_run.tpl, files/tedge/self_update.sh, files/tedge/self_update.toml, tests/main/self-update.robot
Support transferring more docker run options by using the golang template format which is supported by the `docker inspect <container> --format "<template>"` syntax.
The new template supports transferring more docker run options than previously to ensure the new container is spawned in a very similar manner as the previous container
=> feat(self-update): use docker template to generate docker run options

Dockerfile, README.md, docker-compose.yaml, examples/docker-compose.yaml, files/mosquitto/mosquitto.conf, files/tedge/plugins/tedge-log-plugin.toml, justfile, tests/main/self-update.robot
:boom: Breaking change!
Change the data persistence path and name from `/mosquitto/data` to `/data/tedge` as the volume was being used to store both mosquitto and tedge data, and using tedge aligns with naming convention used on physical devices that have firmware_update support.
=> refactor! Change persistence volume name from mosquitto to tedge

files/tedge/self_update.sh
When an update fails and the container is rolledback, collect the logs from the failed container to make it easier to debug why it failed.
=> feat(self-update): collect logs from unhealthy container before removing it

files/tedge/self_update.sh
Robustness improvements for failed updates:
* Only collect last 500 lines of the updater log to prevent cases where the updater produces a large number of log lines
* Increase the delay on failed health checks before retrying to give the container a chance to initialize and connect to the cloud
=> feat(self-update): improve healthcheck and updater log file collection

Dockerfile, files/tedge/container-logs.sh, files/tedge/log_upload.toml, files/tedge/log_upload_container.toml, files/tedge/plugins/tedge-log-plugin.toml, tests/main/operations.robot
Support collecting container log files via the `container` log file type.
A custom log_upload workflow is used to check if the log file type is file based, or command based. An additional workflow for `log_upload_container` is provided to handle the logic about fetching the logs for the given container (specified via the `Filter By Text` UI entry). This allows the user to request log files from ANY running container.
If the `Filter By Text` is left empty by the user, then tedge container logs will be returned.
=> feat: add container log file handler

justfile
=> chore: bump tedge version to 1.3.1

cont-init.d/50_configure.sh
Support loading the device certificate from different sources:
* From base64 encoded environment variables (`CERTPRIVATE` and `CERTPUBLIC`)
* From docker secrets, called `certificate_private_key` and `certificate_public_key`
* From file (e.g. using a volume which contains an already created certificate)
The first found certificate (regardless if it is valid or not) will be taken.
=> feat: support loading device certificate from multiple locations (env, secrets, file)

files/tedge/container-logs.sh
Fix a bug with the retrieval of the container logs via thin-edge.io, where the stderr was not being included (only stdout). Now both stdout and stderr output streams are captured.
=> fix(log_upload): redirect stderr to stdout when collecting container logs

files/tedge/container-logs.sh
Uploading logs to the thin-edge.io file transfer service required redirection to be active to allow redirection from http to https.
=> fix(log_upload): allow url redirects to support cert based auth

README.md, justfile
Add extra instructions for running the project locally.
=> dev: update development instructions

README.md
The step incorrectly states that the cert was stored under a host directory instead of a docker volume
=> docs: update info about where the container is stored

Dockerfile, tests/main/operations.robot
Use the `tedge-container-plugin-ng` plugin to manage and monitor containers.
=> feat: use tedge-container-plugin-ng to manage containers

Dockerfile, tests/main/operations.robot
Due to a bug in the tedge-container-plugin-ng s6-overlay definition, services representing the containers  wasn't being created due to a permissions problem.
The system test now covers the functionality.
=> test: add coverage for service creation after installing a container

Dockerfile
Ensure environment variables are passed to the tedge-container-plugin service
=> fix: support tedge-container-plugin service running as sudo

Dockerfile, files/tedge/self_update.sh, test-images/common/container-bundle.sh, tests/main/self-update-compat.robot, tests/resources/common.resource
Add back in the `self_update.sh` script as it is still called when updating from older images to the new one.
=> fix(self-update): add compatibility script to update from older versions

Dockerfile, docs/FEATURES.md, tests/main/self-update-compat.robot, tests/main/self-update.robot
Container self updating is now supported by the `container` sm-plugin type instead of `self`. The `self` type is no longer part of the container image.
=> feat(self-update): support self update via container sm-plugin type

docs/FEATURES.md, files/tedge/launch-remote-access.sh, files/tedge/self_update.toml, test-images/debian-systemd-podman-cli/Dockerfile, tests/main/container.robot
Use predictable names for:
* c8y-remote-access-plugin connections containers
* self update orchestrator. This allows the inclusion of the updater logs within the workflow.
=> feat: use predictable container names for remote access and self updates

files/tedge/self_update.toml, tests/main/self-update.robot
Remove the self-update container after the self update has completed (and the logs have been collected from it).
=> fix(self-update): remove updater container after collecting logs

Dockerfile
Use new generic tedge-command-plugin which uses a new thin-edge.io 1.4.0 feature which allows custom operation handlers to use thin-edge.io workflows.
=> feat: switch from c8y-command-plugin to tedge-command-plugin

docs/CONTAINER_OPTION2.md
Add section to walk users through bootstrapping the container at runtime (rather than requiring them to configure the container via once-off containers that re-use the shared volumes).
=> docs: add notes about runtime bootstrapping of option 2

Dockerfile
Removing the volume declarations gives more control to the user who they want to mount volumes, and it avoid anonymous volumes from being created
=> feat: remove volume directives from dockerfile

justfile
Remove the latest tag from the test container images to avoid the image's other tags being removed during image pruning.
=> ci: remove latest tag from test container image

Dockerfile, tests/main/files/tedge-configuration-plugin.v2.toml, tests/main/operations.robot
Add the `tedge-write` utility to the sudoers.d/tedge definition to allow the tedge-configuration-plugin to set the file ownership and permissions when writing a file to the container.
A system test was also added to cover this use-case in the future.
=> fix: add tedge-write to tedge's sudoers rule

cont-init.d/50_configure.sh
When using the upcoming PKCS11 (cryptoki) format, the private key is no longer required, as it is stored in a HSM and made available for signing via the PKCS11 interface.
Note: The PKCS11 support is an upcoming feature of thin-edge.io 1.5.0.
=> feat: make private key optional when setting from env variables

Dockerfile, cont-init.d/50_configure.sh, files/tedge/fix-permissions.sh
Use a fixed user id and group id (matching the defaults used in Yocto and Rugix), so that it is easier to share files and sockets from the host to the container (as the container uses a non-root user by default).
=> feat: use fixed user id and group id to easy sharing of files from host to container

docs/CONTAINER_OPTION2_with_hsm.md
Add initial (untested) instructions on how to use thin-edge.io using the tedge-container-bundle-main image with a HSM running on a device with the new **tedge-p11-server** component (which needs to be run on the host!).
=> docs: add initial documentation on how to use container with a HSM

justfile
Update default version to thin-edge.io 1.5.0
=> chore: update to tedge 1.5.0

Dockerfile, justfile
Update to thin-edge.io 1.5.1 by default
=> chore: update to thin-edge.io 1.5.1

README.md, cont-init.d/50_configure.sh, docker-compose.yaml
Add option to register container using the Cumulocity certificate-authority feature, but the feature is disabled by default at the moment.
=> feat: add option to register container using the Cumulocity certificate-authority feature

Dockerfile, README.md, docker-compose.yaml
Add some notes to the readme to guide new users how to use the new Cumulocity certificate-authority feature and how to set the device id and one-time password.
=> feat: add doc notes to the Cumulocity certificate-authority feature

README.md, docs/CONTAINER_OPTION2_with_ca.md
Add new option for user instructions to use the newer Cumulocity certificate authority feature (still in public preview)
=> docs: add user instructions for the c8y ca

docs/CONTAINER_OPTION2_with_ca.md
Fix the example showing how to use the tedge-container-bundle with the Cumulocity Certificate Authority feature
=> docs: fix docker compose example when using c8y ca

Dockerfile, README.md, cont-init.d/50_configure.sh, docs/CONTAINER_OPTION2_with_basic_auth.md, files/tedge/set-c8y-basic-auth.sh, test-images/common/container-bundle.sh, tests/main/c8y-basic-auth.robot, tests/main/self-update.robot, tests/requirements.txt, tests/resources/common.resource
Add support for connecting the tedge-container-bundle to Cumulocity using basic auth instead of certificates.
Certificates are still the preferred method, however it allows users more options to connect to Cumulocity.
=> feat: add support Cumulocity basic auth
